package com.kriogenik.guzeeva.resources

enum class StringResources: Resource {

    REGISTRATION_HELLO_MESSAGE,
    REGISTRATION_ERROR_INVALID_CODE,
    REGISTRATION_ERROR_CODE_ALREADY_USED,
    REGISTRATION_SUCCESS_ENTER_CODE,

    REGISTRATION_ENTER_YOUR_NAME,
    REGISTRATION_ERROR_NUMBERS_IN_NAME,
    REGISTRATION_ERROR_NAME_IS_TOO_LONG,
    REGISTRATION_ERROR_NAME_IS_TOO_SHORT,
    REGISTRATION_SUCCESS_ENTER_NAME,

    REGISTRATION_ENTER_YOUR_AGE,
    REGISTRATION_ERROR_AGE_IS_TOO_YOUNG,
    REGISTRATION_ERROR_AGE_IS_TOO_OLD,
    REGISTRATION_ERROR_LETTERS_IN_AGE,
    REGISTRATION_SUCCESS_ENTER_AGE,

    REGISTRATION_ENTER_YOUR_SEX,
    REGISTRATION_SUCCESS_ENTER_SEX,

    REGISTRATION_ENTER_YOUR_PREFERENCES,
    REGISTRATION_SUCCESS_SELECTED_PREFERENCE,

    REGISTRATION_ENTER_YOU_BIO,
    REGISTRATION_ERROR_BIO_IS_EMPTY,
    REGISTRATION_ERROR_BIO_IS_TOO_LONG,
    REGISTRATION_ERROR_BIO_IS_TOO_SHORT,

    REGISTRATION_SUCCESS_ENTER_BIO,

    REGISTRATION_COMPLETED,

    USER_TO_MENU_BUTTON,

    USER_MAIN_MENU,
    USER_SEARCH_BUTTON,
    USER_SHOW_BIO_BUTTON,
    USER_SHOW_HELP_BUTTON,
    USER_EXIT_BUTTON,

    USER_CHANGE_NAME_BUTTON,
    USER_CHANGE_AGE_BUTTON,
    USER_CHANGE_BIO_BUTTON,
    USER_CHANGE_SEX_BUTTON,
    USER_CHANGE_PREFERENCE_BUTTON,

    NEW_REQUEST_TITLE,
    NEW_REQUEST_ACCEPT_BUTTON,
    NEW_REQUEST_DECLINE_BUTTON,

    USER_WAITING_RESPONSE,
    USER_ANSWERING_REQUEST,

    USER_REQUEST_SEND_SUCCESS,

    USER_SEND_REQUEST_BUTTON,

    USER_SEARCH_NEXT_BUTTON,

    USER_SEARCH_NO_CANDIDATES,

    USER_EXIT_SUCCESS,
    USER_RETURN_BUTTON,

    USER_HELP,

    NEXT_PROFILE_BUTTON_TEXT,

    USER_SEARCH_NEW_CANDIDATE,

    ANSWER_REQUEST_CONFIRM_INITIAL,
    ANSWER_REQUEST_CONFIRM_TARGET,

    ANSWER_REQUEST_DECLINE_INITIAL,
    ANSWER_REQUEST_DECLINE_TARGET,

    ANSWER_NO_FREE_TABLES,

    USER_REQUEST_CANCELED_TARGET,
    USER_REQUEST_CANCELED_INITIAL,

    USER_STOP_TALKING_BUTTON,
    USER_STOP_TALKING_INITIAL,
    USER_STOP_TALKING_TARGET,

    USER_TIME_IS_OVER,

    USER_CANCEL_REQUEST,

    ADMIN_SUCCESS_REGISTRATION,
    ADMIN_MAIN_MENU,
    ADMIN_TO_MENU_BUTTON,
    ADMIN_TO_TABLES_MENU_BUTTON,
    ADMIN_GET_KEY_BUTTON,
    ADMIN_MENU_FREE_TABLE_BUTTON,
    ADMIN_MENU_ADD_TABLE_BUTTON,
    ADMIN_NEW_USER_CODE,

    ADMIN_NO_TABLES,

    ADMIN_ENTER_TABLE_CODE,
    ADMIN_ERROR_TABLE_ALREADY_EXIST,
    ERROR_TABLE_ALREADY_FREED,
    ADMIN_SUCCESS_TABLE_ADDED,
    ADMIN_SUCCESS_TABLE_FREED,

    TABLE_TIME_IS_OVER,

    ADMIN_ERROR_TABLE_REMOVING,

    HANDLER_NOT_FOUND,
    ERROR_MESSAGE,

    PREFERENCE_MALE,
    PREFERENCE_FEMALE,
    PREFERENCE_BOTH,
    PREFERENCE_NOT_SELECTED,

    SEX_MALE,
    SEX_FEMALE,
    SEX_NOT_SELECTED,

    PROFILE_TITLE,
    PROFILE_NAME,
    PROFILE_AGE,
    PROFILE_SEX,
    PROFILE_PREFERENCE,
    PROFILE_BIO,


    BACK_TO_SYSTEM_SUCCESS,
    BACK_TO_SYSTEM_ERROR,

    PHOTO_REGISTRATION_MESSAGE,

    PHOTO_MAIN_MENU,
    PHOTO_BIO,
    PHOTO_MAIN_MENU_ADMIN,
    PHOTO_REGISTRATION_FINISHED,
    PHOTO_HELP

}